In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,3,54,3,4,2])

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  3, 54,  3,  4,  2])

In [6]:
np.unique(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 54])

In [7]:
np.sort(arr)

array([ 1,  2,  2,  3,  3,  3,  4,  4,  5,  6,  7,  8,  9, 54])

In [8]:
np.argsort(arr)

array([ 0,  1, 13,  2,  9, 11, 12,  3,  4,  5,  6,  7,  8, 10])

In [9]:
np.where(arr)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]),)

In [26]:
starr = np.array(["pyTHOn","jupyter"])
starr1 = np.array(["NumPY","pandas"])

In [28]:
np.concatenate((starr,starr1))

array(['pyTHOn', 'jupyter', 'NumPY', 'pandas'], dtype='<U7')