In [1]:
# Data Thinking (AI)
# Data is a fuel of AI (oil)
# 
#  

In [2]:
# json, csv, xml types of data

# It may be in numerical data type: salary, age, population, price etc...
# It may be of categorical data type: Developer,  Designer, Male, Female, Red, Blue etc...
# It may be Boolean datatype: True False
# It may be the text datatype: name, courseName, Student, Email etc...

# THESE are the base foundational data for 

In [3]:
# Image data:  a pic of dog, cat or any others 
# Audio video: analysis of video formats, .mp3, .mp4



In [4]:
# Features (inputs) ---> AI models/ Predictions ---> 
# Labels 

# 1. Data collection
# 2. Data Review
# 3. Data Segregation
# 4. Data Cleaning
# 5. Data Preparation
# 6. AI algorithm feed in

In [5]:
numbers =[10,20,30,40,50,60,70,80]
# output --> [15,25,35,45,55,65,75,85]
result = []

for i in numbers:
    result.append(i + 5)
print(result)

[15, 25, 35, 45, 55, 65, 75, 85]


In [11]:
import numpy as np
numbers = np.array([10,20,30,40,50,60,70,80])
print(numbers + 5)
print(numbers ** 2)
print(numbers * 2)

[15 25 35 45 55 65 75 85]
[ 100  400  900 1600 2500 3600 4900 6400]
[ 20  40  60  80 100 120 140 160]
