In [ ]:
# Vectorization
# data reshaping


In [1]:
import numpy as np

In [20]:
numbers = np.array([10,20,30,40,50])
results  =  numbers * 4
print(results)
print(results[(results > 10) & (results < 200)])

[ 40  80 120 160 200]
[ 40  80 120 160]


In [21]:
results > 40 # checking the results which gives the boolean value

array([False,  True,  True,  True,  True])

In [22]:
numbers > 40

array([False, False, False, False,  True])

In [35]:
numbers = [10,20,30,40,50]
for n in numbers:
    if n > 20:
        print("hi")
    else:
        print("Bye")



Bye
Bye
hi
hi
hi


In [36]:
price = np.array([100,200,300,400])
quantity = np.array([2,4,6,8])
total_amount = price * quantity
print(total_amount)


[ 200  800 1800 3200]


In [37]:
# Broadcasting

a = np.array([1,2,3,4,5])
b = 3

print(a * b)
print(a + b)
print(a - b)

[ 3  6  9 12 15]
[4 5 6 7 8]
[-2 -1  0  1  2]


In [42]:
three_d_array = np.array([[1,2],[3,4],[5,6]]) 
mul = 3
three_d_array * mul

array([[ 3,  6],
       [ 9, 12],
       [15, 18]])

In [49]:
# Data reshaping

data = np.array([[1,2,3],[4,5,6],[7,8,9]])
transpose_data = np.transpose(data)
transpose_data

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [61]:
six_t = np.array([1,2,3,4,5,6])
six_t.shape


(6,)

In [65]:
print(six_t.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [68]:
print(six_t.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [70]:
print(six_t.reshape(1,6))

[[1 2 3 4 5 6]]


In [71]:
six_te = np.array([1,2,3,4,5,6,7])
six_te.reshape(7,1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [72]:
six_nine = np.array([1,2,3,4,5,6,7,8,9])
six_nine.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
six_nine.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [98]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.shape)
arr.reshape(-1)

(2, 3)


array([1, 2, 3, 4, 5, 6])

In [94]:
arr.reshape(6,-1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [97]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [103]:
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr1.shape)
print(arr1.reshape(-1))

(3, 3)
[1 2 3 4 5 6 7 8 9]
