In [33]:
# Polynomial regression Integration


In [63]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [35]:
# inconsistent data cha bhane polynomial lagu huncha
df =  pd.read_csv("student_multiple_features.csv")

In [36]:
df

,Student,StudyHours,Attendance,PreviousMarks,FinalMarks
0,Aarav,2,70,38.0,42
1,Sita,3,75,45.0,50
2,Ram,4,80,52.0,58
3,Anisha,5,85,60.0,68
4,Rohan,6,90,68.0,78
5,Priya,7,92,75.0,85
6,Kiran,8,95,82.0,92
7,Nabin,4,78,55.0,60
8,Suman,5,82,63.0,70
9,Alisha,6,88,70.0,79


In [37]:
df["Attendance"] = pd.to_numeric(df["Attendance"], errors= "coerce")
df["PreviousMarks"] = pd.to_numeric(df["PreviousMarks"], errors= "coerce")

df = df.dropna()

In [38]:
df

,Student,StudyHours,Attendance,PreviousMarks,FinalMarks
0,Aarav,2,70.0,38.0,42
1,Sita,3,75.0,45.0,50
2,Ram,4,80.0,52.0,58
3,Anisha,5,85.0,60.0,68
4,Rohan,6,90.0,68.0,78
5,Priya,7,92.0,75.0,85
6,Kiran,8,95.0,82.0,92
7,Nabin,4,78.0,55.0,60
8,Suman,5,82.0,63.0,70
9,Alisha,6,88.0,70.0,79


In [39]:
# Features and Labels separation

X = df[[
    "StudyHours",
    "Attendance",
    "PreviousMarks"	
]]

Y = df["FinalMarks"]

In [40]:
X = X.to_numpy()
Y = Y.to_numpy()

In [41]:
X

array([[ 2., 70., 38.],
       [ 3., 75., 45.],
       [ 4., 80., 52.],
       [ 5., 85., 60.],
       [ 6., 90., 68.],
       [ 7., 92., 75.],
       [ 8., 95., 82.],
       [ 4., 78., 55.],
       [ 5., 82., 63.],
       [ 6., 88., 70.],
       [ 7., 91., 78.],
       [ 8., 96., 85.],
       [ 3., 72., 48.],
       [ 9., 98., 90.],
       [ 5., 86., 66.],
       [ 4., 79., 58.],
       [ 8., 97., 88.],
       [ 5., 84., 64.]])

In [42]:
Y

array([42, 50, 58, 68, 78, 85, 92, 60, 70, 79, 87, 95, 52, 98, 73, 61, 96,
       74])

In [43]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=42)

In [44]:

poly = PolynomialFeatures(
    degree = 2,
    include_bias= False
)
poly

,"include_bias include_bias: bool, default=TrueIf `True` (default), then include a bias column, the feature in whichall polynomial powers are zero (i.e. a column of ones - acts as anintercept term in a linear model).",False
,"degree degree: int or tuple (min_degree, max_degree), default=2If a single int is given, it specifies the maximal degree of thepolynomial features. If a tuple `(min_degree, max_degree)` is passed,then `min_degree` is the minimum and `max_degree` is the maximumpolynomial degree of the generated features. Note that `min_degree=0`and `min_degree=1` are equivalent as outputting the degree zero term isdetermined by `include_bias`.",2
,"interaction_only interaction_only: bool, default=FalseIf `True`, only interaction features are produced: features that areproducts of at most `degree` *distinct* input features, i.e. terms withpower of 2 or higher of the same input feature are excluded:- included: `x[0]`, `x[1]`, `x[0] * x[1]`, etc.- excluded: `x[0] ** 2`, `x[0] ** 2 * x[1]`, etc.",False
,"order order: {'C', 'F'}, default='C'Order of output array in the dense case. `'F'` order is faster tocompute, but may slow down subsequent estimators... versionadded:: 0.21",'C'


In [46]:
poly_x_train = poly.fit_transform(X_train)
poly_x_train

array([[5.000e+00, 8.500e+01, 6.000e+01, 2.500e+01, 4.250e+02, 3.000e+02,
        7.225e+03, 5.100e+03, 3.600e+03],
       [9.000e+00, 9.800e+01, 9.000e+01, 8.100e+01, 8.820e+02, 8.100e+02,
        9.604e+03, 8.820e+03, 8.100e+03],
       [8.000e+00, 9.700e+01, 8.800e+01, 6.400e+01, 7.760e+02, 7.040e+02,
        9.409e+03, 8.536e+03, 7.744e+03],
       [4.000e+00, 7.900e+01, 5.800e+01, 1.600e+01, 3.160e+02, 2.320e+02,
        6.241e+03, 4.582e+03, 3.364e+03],
       [8.000e+00, 9.600e+01, 8.500e+01, 6.400e+01, 7.680e+02, 6.800e+02,
        9.216e+03, 8.160e+03, 7.225e+03],
       [4.000e+00, 8.000e+01, 5.200e+01, 1.600e+01, 3.200e+02, 2.080e+02,
        6.400e+03, 4.160e+03, 2.704e+03],
       [6.000e+00, 8.800e+01, 7.000e+01, 3.600e+01, 5.280e+02, 4.200e+02,
        7.744e+03, 6.160e+03, 4.900e+03],
       [5.000e+00, 8.400e+01, 6.400e+01, 2.500e+01, 4.200e+02, 3.200e+02,
        7.056e+03, 5.376e+03, 4.096e+03],
       [6.000e+00, 9.000e+01, 6.800e+01, 3.600e+01, 5.400e+02, 4.080e+02

In [47]:
poly_x_test = poly.fit_transform(X_test)
poly_x_test

array([[2.000e+00, 7.000e+01, 3.800e+01, 4.000e+00, 1.400e+02, 7.600e+01,
        4.900e+03, 2.660e+03, 1.444e+03],
       [3.000e+00, 7.500e+01, 4.500e+01, 9.000e+00, 2.250e+02, 1.350e+02,
        5.625e+03, 3.375e+03, 2.025e+03],
       [5.000e+00, 8.200e+01, 6.300e+01, 2.500e+01, 4.100e+02, 3.150e+02,
        6.724e+03, 5.166e+03, 3.969e+03],
       [7.000e+00, 9.200e+01, 7.500e+01, 4.900e+01, 6.440e+02, 5.250e+02,
        8.464e+03, 6.900e+03, 5.625e+03]])

In [49]:
model = LinearRegression()
model.fit(poly_x_train,Y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](9,)","[ 0.49, 0.98,-0.6 ,...,-0.05, 0.19,-0.21]"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,1.629
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,9
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(8)
"singular_ singular_: array of shape (min(X, y),)Singular values of `X`. Only available when `X` is dense.","ndarray[float64](9,)","[10618.31, 1016.02, 125.64,..., 0.28, 0.07, 0.01]"


In [50]:
prediction = model.predict(poly_x_test)
prediction

array([40.04279286, 49.08798563, 70.1537724 , 85.3068503 ])

In [51]:
comparision = pd.DataFrame({
    "actual": Y_test,
    "Prediction" : prediction
})

In [52]:
comparision

,actual,Prediction
0,42,40.042793
1,50,49.087986
2,70,70.153772
3,85,85.306850


In [59]:
mae = mean_absolute_error(
    Y_test,
    prediction
)
mae

0.832461052101447

In [61]:
mse = mean_squared_error(
    Y_test,
    prediction
)
mse

1.1950582612474274

In [65]:
rmse = np.sqrt(mse)
print(rmse)

1.0931872032032883


In [67]:
# Next topic: Classification, Logistic regression
# 